baseURL = "http://example.org/"
languageCode = "en-us"
title = "TailwindCSS blank starter"
theme = "tailwindcss"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3